### ISSUE TITLE
Clarify description for rcFile

### ISSUE THREAD

**Issue by blackHatMonkey** [AtomLinter/linter-pylint#199]
Hi I recently began to get the following error:
```
Error: Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python2.7/dist-packages/pylint/__init__.py", line 17, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 1287, in __init__
    linter.read_config_file()
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 636, in read_config_file
    with io.open(config_file, 'r', encoding='utf_8_sig') as fp:
IOError: [Errno 21] Is a directory: '/home/blackhatmonkey/workspace'
    at /home/blackhatmonkey/.atom/packages/linter-pylint/lib/main.js:130:19
```
I was wondering if you could help me figure out the problem.

**Comment by Arcanemagus** [comment]
Looks like that error is being [re-thrown](https://github.com/AtomLinter/linter-pylint/blob/v1.2.2/lib/main.js#L130) from the output of `pylint`. Does `pylint` itself work when you run it on the file in question from the CLI?

**Comment by blackHatMonkey** [comment]
yes `pylint` works from CLI.

**Comment by blackHatMonkey** [comment]
Here is the output of `pylint` from terminal:
```bash
```

**Comment by blackHatMonkey** [comment]
@Arcanemagus I was able to narrow this problem down to using the `Rc File` field. Using either `%p` or `%f` will cause this problem. Not specifying anything works as expected.

**Comment by Arcanemagus** [comment]
@blackHatMonkey This should be fixed in the upcoming v2.0.0 release, if not please let me know!

**Comment by blackHatMonkey** [comment]
@Arcanemagus Thanks for you hard work :smile: :+1: .

**Comment by blackHatMonkey** [comment]
I do still get the error after upgrading to the latest version. I also included a log from the `console` so it might help you:
[error.txt](https://github.com/AtomLinter/linter-pylint/files/882579/error.txt)

**Comment by Arcanemagus** [comment]
What do you have in the `rcFile` setting?

**Comment by blackHatMonkey** [comment]
[pylintrc.txt](https://github.com/AtomLinter/linter-pylint/files/883154/pylintrc.txt)

**Comment by Arcanemagus** [comment]
I meant in the setting in Atom 😉.

**Comment by blackHatMonkey** [comment]
![screenshot_20170330_144424](https://cloud.githubusercontent.com/assets/25112506/24520738/868bca00-1557-11e7-8cb5-d566f8f57636.png)

Both `%p` and `%f` seem to cause the error.

**Comment by Arcanemagus** [comment]
Ah ha! You are just putting the directory in there. `pylint` should already be finding the default file for you, that setting is for is you are using a custom directory that `pylint` normally wouldn't find, or even using a custom name. As such if you are using that setting you need the _full_ path to the file you are trying to use, including the file name.

**Comment by Arcanemagus** [comment]
Sounds like a decent enough request to me, do you have anything better in mind?

**Comment by blackHatMonkey** [comment]
Maybe an example would show users how to properly use it.

**Comment by ddaanet** [comment]
I had a stab at it, and I am not sure how to do it properly.

The documentation already clearly says "Path to the pylintrc file.", it does not say something like "Directory containing the pylintrc file."

An example could just be confusing… The default working directory is the project root, so a sane example would just look like "my-pylintrc" without any path, which could be confusing. A really weird example like "/home/jdoe/my-pylintrc" could be even more confusing, and I would argue you should know if you are in this kind of situation.
