### ISSUE TITLE
Error running Pylint Error: Process execution timed out

### ISSUE THREAD

**Issue by nbonnotte** [AtomLinter/linter-pylint#204]
```
Error running Pylint Error: Process execution timed out
    at C:\Users\Nicolas\.atom\packages\linter-pylint\node_modules\sb-exec\lib\index.js:92:18
```
Is this related those others issues?
* https://github.com/AtomLinter/linter-phpcs/issues/114
* https://github.com/AtomLinter/linter-csslint/issues/95
* https://github.com/AtomLinter/linter-flake8/issues/169

**Comment by willfrey** [comment]
I am also having this problem.

**Comment by fepegar** [comment]
Same here. Atom console:
```
linter-registry.js [sm]:144 [Linter] Error running Pylint Error: Process execution timed out
    at /home/fernando/.atom/packages/linter-pylint/node_modules/sb-exec/lib/index.js:89:18
```

**Comment by Arcanemagus** [comment]
@fepegar Please enable the "Disable execution timeout" if you are running files that are legitimately hitting the limit.

**Comment by fepegar** [comment]
Done, thank you. Maybe it'd be a good idea to add that suggestion to the error message.

**Comment by Arcanemagus** [comment]
Actually that option is just a stop-gap till a better way of handling it was implemented in the support library. That's actually been completed, it seems that it just hasn't been utilized here.

If you were interested in submitting a PR for that, you can find an example [here](https://github.com/AtomLinter/linter-flake8/blob/v2.2.1/lib/main.js#L186). You just need to add a `uniqueKey` to the exec options, and set some really long time out to still catch runaway processes. (That example uses 5 minutes.

**Comment by rklarpit** [comment]
I am still getting the issue. If I disable it, linter shows nothing. Is there a fix
